//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Nuevo.rc
//
#define DLG_Prueba                      9
#define Dlg_Hola                        101
#define DLG_IniciarSesion               101
#define DLG_RegistroVuelos              103
#define IDD_DIALOG1                     105
#define DLG_Principal                   105
#define IDR_MENU1                       107
#define IDD_DIALOG2                     108
#define DLG_AgregarUsuario              108
#define DLG_ModificarUsuario            110
#define DLG_EliminarVuelo               112
#define DLG_ModificarVuelo              114
#define DLG_ConfirmarVuelo              116
#define DLG_ManifiestoVuelo             118
#define DLG_ReporteVuelo                120
#define DLG_RegistroPasajeros           122
#define DLG_PaseAbordar                 124
#define DLG_CompraBoletos               126
#define DLG_CancelarBoletos             128
#define DLG_EliminarUsuario             132
#define DLG_ModificarPasajero           134
#define VR_Generar                      1004
#define VR_HoraOrigen                   1005
#define EU_Eliminar                     1006
#define LBL_TIMER                       1007
#define LBL_TIMER3                      1008
#define IDC_EDIT2                       1009
#define IDC_BUTTON1                     1010
#define IDC_EDIT4                       1010
#define VR_Destino                      1215
#define BTN_Iniciar                     1010
#define VREP_Generar                    1010
#define RP_Aceptar                      1010
#define LBL_TIMER2                      1011
#define VC_Confirmar                    1011
#define RP_Cancelar                     1011
#define VC_Cancelar                     1012
#define IDC_EDIT3                       1012
#define RM_Eliminar                     1013
#define IDC_DATETIMEPICKER1             1013
#define VR_FechaOrigen                  1013
#define VREP_Hora                       1013
#define US_FechaRegistro                1013
#define IDC_DATETIMEPICKER2             1014
#define VREP_FiltroInicio               1014
#define US_FechaRegistro2               1014
#define RM_Actualizar                   1015
#define IDC_BUTTON2                     1015
#define VREP_FiltroIFinal               1015
#define VREP_FiltroFinal                1015
#define VREP_Salida                     1016
#define VR_Generar2                     1016
#define IDC_DATETIMEPICKER3             1017
#define VR_FechaDestino                 1017
#define VREP_Regreso                    1017
#define IDC_DATETIMEPICKER4             1018
#define VR_HoraDestino                  1018
#define VREP_Origen                     1019
#define IDC_EDIT5                       1020
#define VR_NumAsientoTu                 1020
#define VR_NumAsientosTot               1020
#define IDC_EDIT6                       1021
#define VR_NumAsientoEj                 1021
#define IDC_EDIT7                       1022
#define VR_CostoTu                      1022
#define IDC_EDIT8                       1023
#define VR_CostoEj                      1023
#define IDC_EDIT9                       1024
#define VR_Menores                      1024
#define IDC_EDIT10                      1025
#define VR_Mayores                      1025
#define VREP_NumVuelo                   1025
#define VREP_Destino                    1025
#define VR_Guardar                      1026
#define IDC_BUTTON3                     1027
#define US_Username                     1027
#define VR_NumAsientoEj2                1027
#define VREP_Aceptar                    1214
#define US_Edad                         1028
#define VR_Menores2                     1028
#define US_Correo                       1029
#define VR_Mayores2                     1029
#define US_Contrasenia                  1030
#define US_Nombre                       1031
#define US_FechaNacimiento              1032
#define US_Genero                       1033
#define US_Registrar                    1034
#define US_RutaImagen                   1035
#define US_ActualUser                   1036
#define US_ActualImage                  1037
#define US_Img                          1038
#define US_ApellidoP                    1039
#define US_ApellidoM                    1040
#define MD_Username2                    1041
#define MD_Edad2                        1042
#define MD_Correos2                     1043
#define MD_Username                     1056
#define MD_Edad                         1057
#define MD_Correos                      1058
#define MD_Contrasenia                  1059
#define MD_Nombre                       1060
#define MD_ApellidoM                    1061
#define MD_ApellidoP                    1062
#define MD_FechaNacimiento              1063
#define EU_ApellidoM                    1063
#define MD_Nacimiento                   1063
#define MD_Genero                       1064
#define MD_Registrar                    1065
#define MD_Cargar                       1066
#define MD_Img                          1067
#define MD_RutaImagen                   1068
#define US_Cargar                       1069
#define MD_FechaNacimientoNueva         1069
#define MD_Contrasenia2                 1070
#define VR_Origen                       1070
#define MD_NuevoGenero                  1070
#define MD_Nombre2                      1071
#define VR_NumVuelo                     1071
#define MD_FechaRegistro                1071
#define MD_FechaNacimiento2             1072
#define MD_Genero2                      1073
#define VE_Vuelos                       1074
#define MD_RutaImagen2                  1075
#define VE_Origen                       1075
#define VE_FechaOrigen                  1076
#define MD_Img2                         1077
#define VE_HoraOrigen                   1077
#define MD_ApellidoP2                   1078
#define VE_Generar                      1078
#define MD_ApellidoM2                   1079
#define VE_NumVuelo                     1079
#define VE_Destino                      1080
#define VE_FechaDestino                 1081
#define VE_HoraDestino                  1082
#define VE_Menores                      1084
#define VE_Mayores                      1085
#define VE_Eliminar                     1086
#define VE_CostoEj                      1087
#define VE_CostoTu                      1088
#define VE_NumAsientoTu                 1089
#define VE_NumAsientoEj                 1090
#define IDC_CHECK1                      1091
#define VM_Modificar                    1092
#define VM_Vuelos                       1093
#define VM_Mayores                      1094
#define VS_Vuelos                       1094
#define VC_Vuelos3                      1094
#define VM_Menores                      1095
#define VM_CostoEj                      1096
#define VM_CostoTu                      1097
#define VM_NumAsientoTu                 1098
#define VM_NumAsientoTot                1098
#define VM_NumAsientoEj                 1099
#define VM_NumAsientoEj2                1100
#define VM_NumVuelo                     1101
#define VM_Generar                      1102
#define VM_HoraDestino                  1103
#define VM_HoraOrigen                   1104
#define VM_FechaDestino                 1105
#define VM_FechaOrigen                  1106
#define VM_Origen                       1107
#define VM_Destino                      1108
#define VC_Vuelos                       1109
#define VM_FechaOrigen2                 1109
#define VM_FechaDestino2                1110
#define VC_Vuelos2                      1110
#define VC_FechaOrigen                  1111
#define VM_HoraOrigen2                  1111
#define VC_HoraOrigen                   1112
#define VM_HoraDestino2                 1112
#define VC_FechaDestino                 1113
#define VM_Generar2                     1113
#define VC_HoraDestino                  1114
#define VM_Generar3                     1114
#define VC_NumVuelo                     1115
#define VM_Menores2                     1115
#define VC_NumPasajeros                 1116
#define VM_Mayores2                     1116
#define VS_Pasajeros                    1117
#define VM_Destino3                     1117
#define VM_TipoAvion2                   1117
#define VS_NumVuelo                     1118
#define VM_FechaRegistro                1118
#define VS_FechaOrigen                  1119
#define VS_HoraOrigen                   1120
#define VS_FechaDestino                 1121
#define VS_HoraDestino                  1122
#define VS_TipoAvion                    1123
#define VS_Asiento                      1124
#define VC_Apellido                     1125
#define VS_Apellido                     1125
#define VS_Vuelos2                      1126
#define VS_Origen                       1127
#define VREP_Vuelos                     1127
#define VS_Destino                      1128
#define RR_Nombre                       1128
#define RR_ApellidoM                    1129
#define VS_Vuelos3                      1129
#define RR_ApellidoP                    1130
#define RR_FechaNacimiento              1131
#define RR_Genero                       1132
#define RR_Registrar                    1133
#define RR_Nacionalidad                 1134
#define RP_Nombre                       1135
#define RP_ApellidoM                    1136
#define RP_Amaterno                     1136
#define RM_ApellidoM                    1136
#define RP_ApellidoP                    1137
#define RP_Apaterno                     1137
#define RP_Fecha                        1137
#define RM_FechaNacimiento              1137
#define BC_Costo                        1138
#define RP_Boleto                       1138
#define RM_Gen                          1138
#define RP_NumAsiento                   1139
#define BC_Comprar                      1139
#define RP_NumVuelo                     1140
#define BC_NumAsientoTu                 1140
#define RP_Origen                       1141
#define BC_NumAsientoEj                 1141
#define RP_Destino                      1142
#define BC_Menores                      1142
#define BC_Mayores                      1143
#define BC_Origen                       1144
#define BC_FechaOrigen                  1145
#define BC_HoraOrigen                   1146
#define BC_Destino                      1147
#define BC_FechaDestino                 1148
#define BC_NumAsientoTu2                1148
#define BC_NumAsientoTot                1148
#define BC_HoraDestino                  1149
#define BC_Costo2                       1149
#define BC_Estatus                      1150
#define BC_Pasajeros                    1151
#define BC_MetodoPago                   1152
#define BC_NumVuelo                     1153
#define BCAN_Origen                     1154
#define BC_Aletra                       1154
#define BCAN_FechaOrigen                1155
#define BC_NumVuelo3                    1155
#define BC_Anumero                      1155
#define BCAN_FechaSalida                1155
#define BCAN_HoraOrigen                 1156
#define BCAN_Origen3                    1156
#define BCAN_HoraSalida                 1156
#define BCAN_Pasajeros                  1157
#define BCAN_Cancelar                   1158
#define BCAN_Pasajeros2                 1159
#define BCAN_NumVuelo                   1160
#define BCAN_MetodoPago                 1161
#define BCAN_Costo                      1162
#define BCAN_HoraDestino                1163
#define BCAN_Pasajeros3                 1163
#define BCAN_FechaDestino               1164
#define BCAN_Destino                    1165
#define VR_TipoAvion                    1166
#define VM_TipoAvion                    1167
#define VE_TipoAvion                    1168
#define BCAN_TipoAvion                  1169
#define VM_Destino2                     1169
#define BC_TipoAvion                    1170
#define BC_TipoBoleto                   1171
#define IDC_LIST2                       1172
#define IDC_LIST1                       1174
#define RP_Pasajero                     1174
#define IDC_EDIT1                       1176
#define VR_Estatus                      1176
#define RP_Confirmados                  1176
#define EU_Lista                        1177
#define RP_NoConfirmado                 1177
#define EU_Username                     1178
#define EU_Edad                         1179
#define EU_Correos                      1180
#define EU_Nombre                       1181
#define EU_ApellidoP                    1182
#define EU_FechaNacimiento              1183
#define EU_Genero                       1184
#define EU_Img                          1185
#define EU_RutaImagen                   1186
#define RM_Nombre                       1187
#define RM_ApellidoP                    1188
#define RM_Genero                       1190
#define RM_Genero2                      1190
#define RM_Nacionalidad                 1191
#define RP_Apatern                      1193
#define VE_NumAsientosTot               1193
#define VE_NumAsientoEj2                1194
#define VE_Menores2                     1195
#define VE_Mayores2                     1196
#define BC_Pasajero                     1197
#define BC_Nombre                       1198
#define BC_ApellidoM                    1199
#define BC_ApellidoP                    1200
#define BC_Vuelos                       1201
#define BC_Vuelos2                      1202
#define BC_Vuelos3                      1203
#define BC_RadioTurista                 1204
#define BC_RadioEjecutivo               1205
#define VC_Origen                       1206
#define VC_Destino                      1207
#define VC_Vuelos4                      1208
#define VM_Vuelos2                      1209
#define VREP_Destinos                   1210
#define VREP_HoraOrigen                 1211
#define VREP_FechaOrigen                1212
#define VMAN_Vuelos                     1213
#define IDC_COMBO1                      10191
#define VR_Generar3                     10192
#define VM_Origen2                      11682
#define RM_FechaNacimiento2             11921
#define IDC_DATETIMEPICKER5             11922
#define VR_FechaRegistro                11923
#define ID_USUARIOS_AGREGARUSUARIO      40001
#define ID_VUELOS_AGREGAR               40002
#define ID_VUELOS_MODIFICAR             40003
#define ID_VUELOS_ELIMINAR              40004
#define ID_PASAJEROS_REGISTRAR          40005
#define ID_BOLETOS_COMPRAR              40006
#define ID_BOLETOS_CANCELAR             40007
#define ID_BOLETOS_CONFIRMACION         40008
#define ID_VUELOS_CONFIRMACION          40009
#define ID_PASAJEROS_PASEDEABORDAR      40010
#define ID_VUELOS_MANIFIESTO            40011
#define ID_VUELOS_REPORTE               40012
#define ID_SALIR                        40013
#define ID_USUARIOS_MODIFICARUSUARIO    40014
#define ID_PRINCIPAL                    40015
#define ID_INICIO                       40016
#define ID_USUARIOS_ELIMINARUSUARIO     40017
#define ID_USUARIOS_MODIFICARUSUARIO40018 40018
#define ID_PASAJEROS_ELIMINARUSUARIO    40019
#define ID_PASAJEROS_MODIFICARPASAJERO  40020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         40021
#define _APS_NEXT_CONTROL_VALUE         1214
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
